environments:
  Ansible:
    pipelines:
      - ecs-agent-ubuntu-16.04

pipelines:

      ecs-agent-ubuntu-16.04:
         group: Packer
         label_template: "${COUNT}"
         materials:
           mygit:
             git: https://github.com/ukparliament/parliament.uk-packer.git
             branch: master
             auto_update: true

          
         stages:
           - build:
               clean_workspace: true
               jobs:
                 default:
                   tasks:
                     - exec:
                         command: packer
                         arguments:
                           - build
                           - ecs-agent-ubuntu-16.04.json
